### ISSUE TITLE
DT_mbarPression not modify in tag 1.5 zip file

### ISSUE THREAD

**Issue by Nico0084** [fritz-smh/domogik-plugin-weather#5]
Look At tag 1.5 DT_mbarPression is not corrected to DT_mbarPressure !
On dmg_package --install https://github.com/fritz-smh/domogik-plugin-weather/archive/1.5.zip,  json validation fail !

``````
$ dmg_package --install https://github.com/fritz-smh/domogik-plugin-weather/archive/1.5.zip
Start downloading https://github.com/fritz-smh/domogik-plugin-weather/archive/1.5.zip
Download finished
Upgrade a package from a zip file : /tmp/tmpHZdmqP
Error while reading the json file 'None' : Traceback (most recent call last):
  File "/home/admdomo/domogik/src/domogik/bin/package.py", line 507, in is_json_ok
    pkg_json = PackageJson(data = data)
  File "/home/admdomo/domogik/src/domogik/common/packagejson.py", line 164, in __init__
    raise PackageException(exp.value)
PackageException
```: 'Error validating the json: DataType in sensor current_barometer_value is not valid'
``````

**Comment by fritz-smh** [comment]
I close, I will release 1.6 today with this fix
